export interface MenuItem {
  id: string;
  name: string;
  nameNepali?: string;
  category: 'FOOD' | 'BEVERAGE' | 'BAR' | 'LAUNDRY' | 'TAKEOWAY' | 'CUSTOM';
  categoryLabel: string;
  defaultPrice: number;
  unit: string;
  isManualPrice?: boolean;
}

export const RESTAURANT_BAR_CATALOG: MenuItem[] = [
  // --- RESTAURANT & FOOD ---
  {
    id: 'food_cont_bfast',
    name: 'Continental Breakfast Set',
    nameNepali: 'कन्टिनेन्टल ब्रेकफास्ट सेट',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 450,
    unit: 'Set',
  },
  {
    id: 'food_amer_bfast',
    name: 'American Breakfast Set',
    nameNepali: 'अमेरिकन ब्रेकफास्ट सेट',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 500,
    unit: 'Set',
  },
  {
    id: 'food_dal_bhat',
    name: 'Nepali Dal Bhat Set (Veg/Chicken)',
    nameNepali: 'नेपाली दालभात तरकारी सेट',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 450,
    unit: 'Thali',
  },
  {
    id: 'food_chicken_momo',
    name: 'Chicken Momo (Steam / Fried)',
    nameNepali: 'चिकेन म:म: (स्टिम / फ्राइड)',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 300,
    unit: 'Plate (10 pcs)',
  },
  {
    id: 'food_veg_momo',
    name: 'Veg Momo (Steam / Fried)',
    nameNepali: 'भेज म:म: (स्टिम / फ्राइड)',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 220,
    unit: 'Plate (10 pcs)',
  },
  {
    id: 'food_chicken_fried_rice',
    name: 'Chicken Fried Rice',
    nameNepali: 'चिकेन फ्राइड राइस',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 280,
    unit: 'Plate',
  },
  {
    id: 'food_veg_chowmein',
    name: 'Veg Fried Rice / Chowmein',
    nameNepali: 'भेज फ्राइड राइस / चाउमिन',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 220,
    unit: 'Plate',
  },
  {
    id: 'food_chicken_chowmein',
    name: 'Chicken Chowmein',
    nameNepali: 'चिकेन चाउमिन',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 250,
    unit: 'Plate',
  },
  {
    id: 'food_club_sandwich',
    name: 'Club Sandwich with French Fries',
    nameNepali: 'क्लब स्यान्डविच र फ्रेन्च फ्राइज',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 380,
    unit: 'Order',
  },
  {
    id: 'food_pizza',
    name: 'Freshly Baked Pizza (Chicken/Veg)',
    nameNepali: 'पिजा (चिकेन वा भेज)',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 550,
    unit: 'Regular (8")',
  },
  {
    id: 'food_french_fries',
    name: 'Crispy French Fries / Potato Wedges',
    nameNepali: 'फ्रेन्च फ्राइज / आलु वेजेज',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 200,
    unit: 'Portion',
  },
  {
    id: 'food_hot_soup',
    name: 'Hot Soup (Chicken / Mushroom / Tomato)',
    nameNepali: 'तातो सुप (चिकेन/च्याउ/गोलभेडा)',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 220,
    unit: 'Bowl',
  },
  {
    id: 'food_toast_butter',
    name: 'Toast with Butter & Jam (2 slices)',
    nameNepali: 'टोस्ट र बटर/जाम',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 150,
    unit: 'Plate',
  },
  {
    id: 'food_eggs_order',
    name: 'Eggs to Order (Omelette / Scrambled / Boiled 2 pcs)',
    nameNepali: 'अन्डा (अमलेट / उसिनेको)',
    category: 'FOOD',
    categoryLabel: '🍳 Breakfast & Food',
    defaultPrice: 130,
    unit: 'Plate (2 pcs)',
  },

  // --- CAFÉ & HOT BEVERAGES ---
  {
    id: 'bev_masala_tea',
    name: 'Nepali Masala Milk Tea (दूध चिया)',
    nameNepali: 'मसला दूध चिया',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 80,
    unit: 'Cup',
  },
  {
    id: 'bev_black_tea',
    name: 'Black Tea / Green Tea',
    nameNepali: 'कालो चिया / ग्रीन टी',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 60,
    unit: 'Cup',
  },
  {
    id: 'bev_lemon_ginger_honey',
    name: 'Lemon Ginger Honey Tea',
    nameNepali: 'कागति अदुवा मह चिया',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 120,
    unit: 'Cup',
  },
  {
    id: 'bev_americano',
    name: 'Freshly Brewed Americano / Espresso',
    nameNepali: 'अमेरिकानो / एस्प्रेसो कफी',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 160,
    unit: 'Cup',
  },
  {
    id: 'bev_cappuccino',
    name: 'Cappuccino / Café Latte',
    nameNepali: 'कापुचिनो / लात्ते कफी',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 200,
    unit: 'Cup',
  },
  {
    id: 'bev_hot_chocolate',
    name: 'Hot Chocolate Milk',
    nameNepali: 'हट चकलेट',
    category: 'BEVERAGE',
    categoryLabel: '☕ Café & Hot Beverages',
    defaultPrice: 220,
    unit: 'Cup',
  },

  // --- COLD DRINKS & BAR ---
  {
    id: 'bar_mineral_water',
    name: 'Mineral Water (1 Litre Sealed Bottle)',
    nameNepali: 'सिलबन्दी मिनरल वाटर (१ लिटर)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 50,
    unit: 'Bottle',
  },
  {
    id: 'bar_soft_drinks',
    name: 'Soft Drinks (Coca-Cola / Sprite / Fanta)',
    nameNepali: 'कोल्ड ड्रिंक्स (कोक, स्प्राइट, फ्यान्टा)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 120,
    unit: 'Can/Bottle',
  },
  {
    id: 'bar_fresh_juice',
    name: 'Fresh Fruit Juice (Seasonal)',
    nameNepali: 'ताजा मौसमी फलफूलको जुस',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 250,
    unit: 'Glass',
  },
  {
    id: 'bar_beer_gorkha',
    name: 'Gorkha / Tuborg Beer (650 ml Bottle)',
    nameNepali: 'गोर्खा / टुबोर्ग बियर (६५० एमएल)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 550,
    unit: 'Bottle',
  },
  {
    id: 'bar_beer_everest',
    name: 'Everest Premium Lager Beer (650 ml)',
    nameNepali: 'एभरेष्ट बियर (६५० एमएल)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 500,
    unit: 'Bottle',
  },
  {
    id: 'bar_beer_can',
    name: 'Craft / Canned Beer (500 ml)',
    nameNepali: 'क्यान्ड बियर (५०० एमएल)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 420,
    unit: 'Can',
  },
  {
    id: 'bar_wine_glass',
    name: 'House Wine (Red / White - Glass)',
    nameNepali: 'हाउस वाइन (रातो / सेतो - गिलास)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 550,
    unit: 'Glass',
  },
  {
    id: 'bar_wine_bottle',
    name: 'Premium Wine (Full Bottle 750ml)',
    nameNepali: 'वाइन बोतल (७५० एमएल)',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 2500,
    unit: 'Bottle',
  },
  {
    id: 'bar_spirits_peg',
    name: 'Spirits (Rum / Vodka / Whisky Peg 60ml)',
    nameNepali: 'खुकुरी रम / भोड्का / ह्विस्की पेग',
    category: 'BAR',
    categoryLabel: '🍺 Cold Drinks & Bar',
    defaultPrice: 400,
    unit: 'Peg (60ml)',
  },

  // --- LAUNDRY & OUTSIDE TAKEAWAY (MANUAL BILL ENTRY) ---
  {
    id: 'service_laundry',
    name: 'Laundry Service (लन्ड्री सेवा)',
    nameNepali: 'लुगा धुने / इस्त्री गर्ने सेवा',
    category: 'LAUNDRY',
    categoryLabel: '🧺 Laundry Service (लन्ड्री)',
    defaultPrice: 350,
    unit: 'Service',
    isManualPrice: true,
  },
  {
    id: 'service_takeaway',
    name: 'Takeaway / Outside Order (टेक-अवे अर्डर)',
    nameNepali: 'बाहिरबाट मगाएको सामान / खानाको बिल',
    category: 'TAKEOWAY',
    categoryLabel: '🛍️ Takeaway & Outside Purchases',
    defaultPrice: 500,
    unit: 'Order',
    isManualPrice: true,
  },
  {
    id: 'service_custom',
    name: 'Custom Expense / Other Service (अन्य खर्च)',
    nameNepali: 'अन्य म्यानुअल खर्च',
    category: 'CUSTOM',
    categoryLabel: '✍️ Custom Expense',
    defaultPrice: 100,
    unit: 'Item',
    isManualPrice: true,
  },
];
