import { registerJobHandler } from './jobQueue';
import { dispatchAutomatedMessage } from './communicationService';
import { prisma } from './prisma';
import { TaskStatus } from '@prisma/client';

let handlersRegistered = false;

/**
 * Registers all automation job worker handlers.
 * Safe to call multiple times (idempotent).
 */
export function initializeWorkerHandlers() {
  if (handlersRegistered) return;
  handlersRegistered = true;

  // 1. Send Automated Communication (WhatsApp, Email, SMS)
  registerJobHandler('SEND_COMMUNICATION', async (payload) => {
    await dispatchAutomatedMessage({
      reservationId: payload.reservationId,
      guestId: payload.guestId,
      channel: payload.channel,
      templateName: payload.templateName,
      recipient: payload.recipient,
      templateData: payload.templateData,
      requiresStaffAction: payload.requiresStaffAction,
    });
  });

  // 2. Create Housekeeping Task
  registerJobHandler('CREATE_HOUSEKEEPING', async (payload) => {
    const { roomId, taskType = 'Turnover Clean', priority = 'NORMAL', scheduledFor, notes } = payload;
    if (!roomId) return;

    await prisma.housekeepingTask.create({
      data: {
        roomId,
        taskType,
        priority,
        status: TaskStatus.PENDING,
        notes: notes || 'Automated task generated by PMS event engine',
        scheduledFor: scheduledFor ? new Date(scheduledFor) : new Date(),
      },
    });
  });

  // 3. Channel Manager Sync Push
  registerJobHandler('CHANNEL_SYNC', async (payload) => {
    const { roomNumber, channel = 'ALL', action = 'AVAILABILITY_PUSH' } = payload;
    await prisma.otaSyncLog.create({
      data: {
        channel,
        roomNumber: String(roomNumber),
        action,
        status: 'SUCCESS',
        message: `Automated sync push executed for Room ${roomNumber}`,
        details: JSON.stringify(payload),
      },
    });
  });
}
